# Linear Algebra

In [1]:
# matrix multiplication
from numpy import array
# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()
# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()
# Combine Transformations
combined = transform2 @ transform1
# Test
print("COMBINED MATRIX:\n {}".format(combined))
v = array([1, 2])
print(combined.dot(v)) # [-1 1]

COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


In [2]:
rotated = transform1.dot(v)
sheered = transform2.dot(rotated)
print(sheered) # [-1 1]

[-1  1]


## Determinants

In [ ]:
# Simple shears and rotations should not affect the determinant as the area will not change.

In [ ]:
#A determinant on a flipped space is negative
from numpy.linalg import det
from numpy import array
i_hat = array([-2, 1])
j_hat = array([1, 2])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints -5.0

In [ ]:
""" testing for a 0 determinant is highly helpful to determine if a
transformation has linear dependence. When you encounter this you will
likely find a difficult or unsolvable problem on your hands.""""Math for Data Science.ipynb"

i_hat = array([-2, 1])
j_hat = array([3, -1.5])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints 0.0

## Inverse Matriz

In [3]:
# SymPy to study the inverse and identity matrix
from sympy import *
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = Matrix([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
# dot product between A and its inverse
# will produce identity function
inverse = A.inv()
identity = inverse * A
# prints Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
print("INVERSE: {}".format(inverse))
# prints Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print("IDENTITY: {}".format(identity))

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [4]:

# NumPy to solve a system of equations
from numpy import array
from numpy.linalg import inv
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = array([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
B = array([
44,
56,
72
])
X = inv(A).dot(B)
print(X) # [ 2. 34. -8.]

[ 2. 34. -8.]


In [ ]:
from sympy import *
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = Matrix([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
B = Matrix([
44,
56,
72
])
X = A.inv() * B
print(X) # Matrix([[2], [34], [-8]])

## Eigenvectors and Eigenvalues

In [6]:
#Performing eigendecomposition in NumPy
from numpy import array, diag
from numpy.linalg import eig, inv
A = array([
[1, 2],
[4, 5]
])
eigenvals, eigenvecs = eig(A)
print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)
"""
EIGENVALUES
[-0.46410162 6.46410162]
EIGENVECTORS
[[-0.80689822 -0.34372377]
[ 0.59069049 -0.9390708 ]]
"""


EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


'\nEIGENVALUES\n[-0.46410162 6.46410162]\nEIGENVECTORS\n[[-0.80689822 -0.34372377]\n[ 0.59069049 -0.9390708 ]]\n'

In [ ]:
#Decomposing and recomposing a matrix in NumPy
from numpy import array, diag
from numpy.linalg import eig, inv
A = array([
[1, 2],
[4, 5]
])
eigenvals, eigenvecs = eig(A)
print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)
print("\nREBUILD MATRIX")
Q = eigenvecs
R = inv(Q)
L = diag(eigenvals)
B = Q @ L @ R
print(B)
"""
EIGENVALUES
[-0.46410162 6.46410162]
EIGENVECTORS
[[-0.80689822 -0.34372377]
[ 0.59069049 -0.9390708 ]]
REBUILD MATRIX
[[1. 2.]
[4. 5.]]
"""

EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

REBUILD MATRIX
[[1. 2.]
 [4. 5.]]


'\nEIGENVALUES\n[-0.46410162 6.46410162]\nEIGENVECTORS\n[[-0.80689822 -0.34372377]\n[ 0.59069049 -0.9390708 ]]\nREBUILD MATRIX\n[[1. 2.]\n[4. 5.]]\n'

: 